apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: helm-webapp-prod
  namespace: argocd
spec:
  destination:
    namespace: helm-webapp-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm-webapp
    repoURL: https://github.com/iurie-bogdanovici/argo-examples.git
    targetRevision: HEAD
  syncPolicy: {}
