apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kustomize-webapp-prod
  namespace: argocd
spec:
  destination:
    namespace: kustomize-webapp-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustom-webapp/overlays/prod
    repoURL: https://github.com/iurie-bogdanovici/argo-examples.git
    targetRevision: HEAD
  syncPolicy: {}
