apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kustomize-webapp-dev
  namespace: argocd
spec:
  destination:
    namespace: kustomize-webapp-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustom-webapp/overlays/dev
    repoURL: https://github.com/iurie-bogdanovici/argo-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
